### ISSUE TITLE
Lacks for newbies

### ISSUE THREAD

**Issue by JulienMEME** [willylambert/vitaminewall#3]
Thanks you soo much for this brightness application!

I am discovering Processing through VitamineWall, and I had some difficults to launch vitaminewall.pde wich combined with others PDE files ('class no find'...). Can you explain quickly how to add this project in  us sketchbook or how to change sketchbook path (which parent directory to select)?

And I saw than you have a path in hard code in vitaminewall.pde:
wall1.png
 but the refered picture does not exist in the root project (and not in data...). Is-it a problem?

I let available for you to any precisions.
Thanks again.

**Comment by willylambert** [comment]
Hi,

First, after download you have to check that the folder is named "vitaminewall" (same name as the main sketch `vitaminewall.pde`)

Then, you have to install the following libraries (Sketch => Import Library) :
* Sound
* Video
* ControlP5

The reference to `wall1.png` is no longer needed, as the wall editor is now embedded in the application.

Tell me if it works !
