### ISSUE TITLE
No such Gstreamer factory: v4l2src

### ISSUE THREAD

**Issue by Rom1deTroyes** [willylambert/vitaminewall#8]
Le Bonjour !

J'essaie d'installer Vitamine Wall sur une Debian 9.4 (stretch stable de base + quelques bricoles), et j'ai une erreur `No such Gstreamer factory: v4l2src`.

J'ai essayé la version [relase](https://github.com/willylambert/vitaminewall/releases/download/v0.1/vitamineWall-linux64.zipl) et en clonant le dépôt Github :

**Version relase**

- Les fenêtres de contrôles s'ouvrent mais restent grises.
- la fenêtre VP affiche bien "La caméra me voit ?".
- La console affiche l'erreur suivante : 
```
ERROR: /node/free: Node id -1 out of range
java.lang.IllegalArgumentException: No such Gstreamer factory: v4l2src
	at org.gstreamer.ElementFactory.makeRawElement(ElementFactory.java:205)
	at org.gstreamer.ElementFactory.make(ElementFactory.java:92)
	at processing.video.Capture.listResolutions(Unknown Source)
	at processing.video.Capture.list(Unknown Source)
	at processing.video.Capture.list(Unknown Source)
	at vitaminewall$UIControl.setup(vitaminewall.java:1271)
	at processing.core.PApplet.handleDraw(PApplet.java:2412)
	at processing.awt.PSurfaceAWT$12.callDraw(PSurfaceAWT.java:1547)
	at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:316)
```
![](https://framapic.org/W5HXxm0vYumR/DfrrDtnmIpL9)

**Version Github**

- Installation et lancement de processing-3.3.7 depuis processing.org et ajout des 3 bibliothèques (Sound 1.4.0, Video 1.0.1, ControlP5 2.2.6 )
- Clone et ouverture Vitaminewall master (Latest commit 0ae7803)
- Au lancement du projet :
  - La fenêtre VP affiche "Bricolab présente Vitamine Wall" (data/welcome.png)
  - Les autres fenêtres sont grises, mais si j'en passe une en plein écran, j'ai bien l'image de la webcam qui s'affiche
 - La console affiche :
![](https://framapic.org/gavjNmCbhC9O/Z4INSPaytESp.png)

**Informations complémentaires**

- Machine : Core2Duo 3GHz, 4G Ram
- Webcam : logitech HD 720p
- Système : GNU/Linux Linux Debian 4.9.82-1+deb9u3 (2018-03-02) / i3wm 4.13
- Java : openjdk version "1.8.0_151" / OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-1~deb9u1-b12) / OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)

Une idée de par où commencer à chercher quoi ?

++
    Romain

**Comment by willylambert** [comment]
Bonjour Romain,

Pour commencer, il faut utiliser la version de la branche master. 

@JulienMEME  a déjà remonté ce problème de fenêtres qui restent grises sous environnement Linux. Il semble apparaître aléatoirement, et je ne l'ai jamais constaté sur mon environnement Windows 10.

Je pencherai pour un problème de driver de caméra ...

Quelques tests à effectuer : 
* La caméra supporte la résolution de 640 x 680 ?
* Tester le Vitamin' Wall sous Windows avec la même caméra
* Essayer avec une "vieille" caméra.

J'ai une caméra 720p  - je vais faire quelques tests de mon coté.

Cela semble être le même problème que celui décrit ici : 
https://github.com/processing/processing-video/issues/23

**Comment by willylambert** [comment]
@Rom1deTroyes @JulienMEME Nouvelle version dans le master à essayer : la phase de chargement des caméras est désormais explicite (plus d'écrans gris)
